### ISSUE TITLE
After clicking Prev or Next and the next page loads, it should be scrolled to the top

### ISSUE THREAD

**Issue by jeffslofish** [jeffslofish/open-source-help-wanted#19]

**Comment by zootechdrum** [comment]
Hello, are you still looking for help on this issue. I would like to give this a go!

**Comment by jeffslofish** [comment]
Yes, please give it a shot!

**Comment by jeffslofish** [comment]
How did you find out about this project?

**Comment by zootechdrum** [comment]
Hey @jeffslofish, I just saw the issue searching through GItHub. Thanks! I think based on the title of this issue it's clear what needs to happen. I will let you know if I have any questions. Please assign this to me when you can.
