### ISSUE TITLE
Dropdowns not displaying correctly

### ISSUE THREAD

**Issue by jeffslofish** [jeffslofish/open-source-help-wanted#24]
![Screen Shot 2020-06-08 at 11 35 57 PM](https://user-images.githubusercontent.com/1240484/84114239-ddf7e280-a9e0-11ea-9bbd-5db12e78afba.png)

**Comment by jeffslofish** [comment]
Only does this in mobile mode

**Comment by jeffslofish** [comment]
Should have clear contrast no matter if you are in mobile or desktop mode.

**Comment by shubhdwiv12** [comment]
hey jeff, i am new into open source, and i wanted to work on this issue, can you exactly specify , what problem you are facing in it.

**Comment by jeffslofish** [comment]
@shubhdwiv12 Thank you for looking into this, but I believe the issue is resolved with PR #31.
