### ISSUE TITLE
This project could use a logo

### ISSUE THREAD

**Issue by jeffslofish** [jeffslofish/open-source-help-wanted#26]

**Comment by chris-hjelmfelt** [comment]
Would you like a favicon and logo like these?  ![favicon](https://user-images.githubusercontent.com/14955626/86196531-4d588200-bb08-11ea-98d6-adaba35bf251.png)
![help_wanted](https://user-images.githubusercontent.com/14955626/86196541-50ec0900-bb08-11ea-8b2b-73b5f920173f.png)
If not, tell me what you had in mind. I like this project and would like to help it grow.

**Comment by jeffslofish** [comment]
Hi @chris-hjelmfelt, thanks for your input. Do you think it would be possible to make a favicon that has all four letters (OSHW), arranged in a square shape, or would that make the letters too small? 

Also, do you have any other ideas for the logo? It would be nice to have a few different ideas to pick from. 

Thanks!

**Comment by chris-hjelmfelt** [comment]
I don't know if I can do that with the favicon but I will try. I'm happy to create a couple more logo designs for you to look at.

**Comment by chris-hjelmfelt** [comment]
![OSHW_favicon_16](https://user-images.githubusercontent.com/14955626/88870802-84878500-d1d3-11ea-9a40-a6594395e26e.png)
I made the colors match better. It's not super clear but not too bad. What do you think? Should I go ahead and replace the React icon or do you have another suggestion?

**Comment by jeffslofish** [comment]
Yeah, if you want to replace the react icon, that would be great!

**Comment by chris-hjelmfelt** [comment]
Here are some logo ideas:
![OSHW_Logo_02](https://user-images.githubusercontent.com/14955626/89462045-16d6de00-d72a-11ea-9ae5-f4593cefc32e.png)
![OSHW_Logo_03](https://user-images.githubusercontent.com/14955626/89462049-19d1ce80-d72a-11ea-84b2-b585a828b50b.png)
![OSHW_Logo_04](https://user-images.githubusercontent.com/14955626/89462057-1b9b9200-d72a-11ea-94ea-d20c5c97c1d6.png)
![OSHW_Logo_05](https://user-images.githubusercontent.com/14955626/89462060-1dfdec00-d72a-11ea-956e-4bf60ec58cac.png)
![OSHW_Logo_06](https://user-images.githubusercontent.com/14955626/89462066-1fc7af80-d72a-11ea-8c96-cd57b4d516bf.png)
![OSHW_Logo_07](https://user-images.githubusercontent.com/14955626/89462073-222a0980-d72a-11ea-9ab6-de09d41289f4.png)
If you like the searching logo it looks decent as a favicon too:
![searching_a_list_16](https://user-images.githubusercontent.com/14955626/89462136-38d06080-d72a-11ea-9c73-fb22c9bedbb0.png)
I can modify colors and such if you like certain elements from different ones

**Comment by jeffslofish** [comment]
I do like the searching logo! This one: 
![logo](https://user-images.githubusercontent.com/1240484/89478087-d1270f00-d743-11ea-8f4e-962f6b0c3d10.png)

Can you update the code to use that, and the favicon too?

**Comment by chris-hjelmfelt** [comment]
My favorites were the two with the searching logo :) 
I will get it added.

**Comment by jeffslofish** [comment]
Closed via #40
