### ISSUE TITLE
Make labels more legible

### ISSUE THREAD

**Issue by jeffslofish** [jeffslofish/open-source-help-wanted#3]
Right now the label color is being pulled from the Github api results, and the font color is always white. We could possibly display a lighter or darker color depending on the color of the label. There appears to be a few javascript implementations of the algorithm that chooses the font color out on the web. Need to investigate further.

**Comment by FelixHenninger** [comment]
I'd be glad to help with this! (probably sometime around the end of next week -- if anybody gets around to doing it sooner, please don't wait for me, though). I'll probably look at the algorithms first (there seem to be several options), and make a brief overview before implementing one.

**Comment by FelixHenninger** [comment]
I just found [Chromatism](https://github.com/toish/chromatism), which implements the [W3C recommendations](http://www.w3.org/TR/WCAG20/) for selecting the text color [based on luminance](https://stackoverflow.com/a/3943023). Would you be ok with pulling in this library as a dependency?

There are easier (and leaner) ways of approximating the algorithm using RGB values alone, if you would prefer such a solution. It's probably not worth the effort to reimplement the luminance conversion. What do you think?

**Comment by jeffslofish** [comment]
Sure, we could add Chromatism!

**Comment by jeffslofish** [comment]
@FelixHenninger Thanks for the suggestion on using Chromatism! I finally (after two years) implemented your suggestion, and it works great! 🥇

**Comment by FelixHenninger** [comment]
Very nice, kudos on the awesome updates 👍 -- keep up the awesome work, and let me know if you're doing another sprint sometime!
