### ISSUE TITLE
Exclude repos that automate fake issues

### ISSUE THREAD

**Issue by chris-hjelmfelt** [jeffslofish/open-source-help-wanted#36]
There is a repo on our list -  pddemo/demo, that is automating fake issues once per minute and then deleting them. We should exclude it. If there is a way to automatically recognize this issue in other repos it would be great to have a test for that.

**Comment by chris-hjelmfelt** [comment]
GitHub Learning Lab also creates fake issues when people go through the tutorial. These two types of fake issues require a different method of removing them so maybe we can't exclude things automatically but I will remove these two types.

**Comment by chris-hjelmfelt** [comment]
So I'm thinking I would add a checkbox in the search parameters for excluding known fake issues. I think it should be checked by default so people looking at the list for the first time don't get all the junk, but then if people are worried something important is excluded they can run the search again with it unchecked. Do you like this approach?

**Comment by jeffslofish** [comment]
Yeah that sounds good. Probably put it under the advanced search options.
