### ISSUE TITLE
Avatar shows the person opening the issue but links to the repo owner when clicked

### ISSUE THREAD

**Issue by chris-hjelmfelt** [jeffslofish/open-source-help-wanted#38]
Is this the desired behavior? 
It seems a bit confusing. It seems like either we should show the avatar for the repo owner, or have the link for the avatar go to the person shown, or not have the avatar link to anything.

**Comment by jeffslofish** [comment]
Good catch! It would be nice if the avatar linked to the person shown.

**Comment by jeffslofish** [comment]
@chris-hjelmfelt are you working on this issue at all? If you are, I can assign it to you, otherwise I'll leave it open for others to take.

**Comment by chris-hjelmfelt** [comment]
I'm not working on it right now so you can leave it open.
