### ISSUE TITLE
[feature request] save as a link

### ISSUE THREAD

**Issue by 1ucian0** [jeffslofish/open-source-help-wanted#49]
It would be great if you could generate an URL out of your search. That would allow to put that as a link in websites. Something like: `https://www.opensourcehelpwanted.com/?labels=good+first+issue&Org=Qiskit`

Awesome work btw!

**Comment by jeffslofish** [comment]
Hi @1ucian0, I just implemented your feature request. Let me know how you like it, and thanks for the suggestion!
