### ISSUE TITLE
Have option to exclude upptime/uptime issues 

### ISSUE THREAD

**Issue by jeffslofish** [jeffslofish/open-source-help-wanted#61]
similar to the 'Exclude known fake issues" checkbox under advanced options.

![Screen Shot 2022-09-02 at 12 45 28 AM](https://user-images.githubusercontent.com/1240484/188085773-eec04d3d-cc23-444b-b6c0-89ff847ba7b1.png)

**Comment by rashmisubhash** [comment]
Can I take up this issue?

**Comment by rashmisubhash** [comment]
Getting this issue when running the project

![image](https://user-images.githubusercontent.com/29196787/188250423-df49f2aa-dd4e-4344-8688-a470cb3a4bac.png)

**Comment by jeffslofish** [comment]
Hmm, I'm going to try to start over from scratch and follow the README and see if I get that too...., one sec..

**Comment by jeffslofish** [comment]
Hmm it is working for me.... Did you follow the README and create the .env file with the OAUTH secret/id ? What operating system are you using?

**Comment by rashmisubhash** [comment]
Yes, I created and added it to the .env file. I use windows

**Comment by jeffslofish** [comment]
I use macOS, I wonder if something is not compatible right now with Windows?

**Comment by rashmisubhash** [comment]
I followed all the steps exactly!! I forked and then cloned, only difference

**Comment by jeffslofish** [comment]
I'm sorry for your trouble....I have a Windows VM I can try it on and see if I get the same error...

**Comment by rashmisubhash** [comment]
No problem, let me know where I am going wrong

**Comment by jeffslofish** [comment]
Ok, it's a bug in the code. It is looking for a local storage item that doesn't exist. Let me fix that right now. Thank you for helping find this!

**Comment by jeffslofish** [comment]
Alright, it should be fixed now if you pull the latest code from main.

**Comment by rashmisubhash** [comment]
Working, thanks. What needs to be done here?

**Comment by jeffslofish** [comment]
So I think what we need to do is create another checkbox below "Exclude known fake issues" that is checked by default and it filters out any issues coming from repos with the name of "upptime" or "uptime"

**Comment by jeffslofish** [comment]
Because those issue are just uptime status issues that are automatically generated. They are not real issues that someone would want to work on for an open source project.

**Comment by rashmisubhash** [comment]
Okay, what should the name of the checkbox be?

**Comment by jeffslofish** [comment]
Maybe, "Exclude status issues"
